kind: Deployment
apiVersion: apps/v1
metadata:
  name: bookish-telegram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookish-telegram
  template:
    metadata:
      labels:
        app: bookish-telegram
    spec:
      containers:
        - name: bookish-telegram
          image: bookish-telegram/hello
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          restartPolicy: Always
