apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-deployment
  labels: 
    app: chatws
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: chatws
  template: 
    metadata:
      labels: 
        app: chatws
    spec: 
      containers:
      - name: chatws
        image: cashelbloom/img-messagedb:v1.0
        ports:
        - containerPort: 80
