apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-deployment
  labels: 
    app: chatmsg
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: chatmsg
  template: 
    metadata:
      labels: 
        app: chatmsg
    spec: 
      containers:
      - name: chatmsg
        image: cashelbloom/img-messagedb:v1.0
        ports:
        - containerPort: 9999
